name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test'
        required: false
        default: 'main'

jobs:
  test:
    if: ${{ github.event_name == 'push' }}
    uses: jamesmortensen/chromedriver-action-tester/.github/workflows/chrome.yml@main
  
  test_wd:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: jamesmortensen/chromedriver-action-tester/.github/workflows/chrome.yml@${{ inputs.version }}
